# Generated by Django 3.2.9 on 2021-11-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvgPriceByBrand',
            fields=[
                ('brand', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('avg_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'avg_price_by_brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvgPriceByCategory',
            fields=[
                ('category', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('avg_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'avg_price_by_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryOccurrence',
            fields=[
                ('word', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category_occurrence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpensiveFurniture',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expensive_furniture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HasImage',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'has_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoNull',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'no_null',
                'managed': False,
            },
        ),
    ]
